[package]
name = "driver-inputs"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
csv = { workspace = true }
iracing-sdk = { workspace = true }
iracing-sdk-derive = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
